source 'http://rubygems.org'

gem 'rubygems-update'
gem 'bundler'
gem 'sinatra'
gem 'rest-open-uri'
gem 'json'
gem 'rest-client'
gem 'shotgun'
gem 'dotenv'
gem 'google-api-client', '>0.7'
gem 'trollop'